// script.js
document.addEventListener('DOMContentLoaded', () => {
    const weekRows = document.querySelectorAll('.week-row');
    const dailyTasks = document.getElementById('daily-tasks');
    const weekNumber = document.getElementById('week-number');
    const taskContent = document.getElementById('task-content');
  
    // Define daily tasks for each week with specific resource links
    const tasks = {
      1: [
        { day: 1, reading: 'Skim 1 passage, answer 10 questions (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Listen to 1 section, note key points (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Study Task 1 structure (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>), write 1 paragraph', speaking: 'Practice 1 Part 1 question, record yourself (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        // Repeat for days 2-7 with similar structure, rotating resources (IELTS Official, Cambridge, IELTS Liz, etc.)
        { day: 2, reading: 'Skim 1 passage, answer 10 questions (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Listen to 1 section, summarize (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Study Task 1 structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>), write 1 paragraph', speaking: 'Practice 1 Part 1 question (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 3, reading: 'Skim 1 passage, answer 10 questions (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Listen to 1 section, note key points (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write 1 Task 1 paragraph (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 Part 1 question (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 4, reading: 'Skim 1 passage, answer 10 questions (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Listen to 1 section, summarize (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Study Task 1 structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 Part 1 question (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 5, reading: 'Skim 1 passage, answer 10 questions (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Listen to 1 section, note key points (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write 1 Task 1 paragraph (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 Part 1 question (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 6, reading: 'Skim 1 passage, answer 10 questions (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Listen to 1 section, summarize (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Study Task 1 structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 Part 1 question (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 7, reading: 'Skim 1 passage, answer 10 questions (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Listen to 1 section, note key points (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write 1 Task 1 paragraph (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 Part 1 question, review recording (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
      ],
      2: [
        { day: 8, reading: 'Skim 2 passages, answer 15 questions (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Listen to 2 sections, summarize (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Study Task 2 structure (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>), write 2 paragraphs', speaking: 'Practice 1 Part 2 question, focus on fluency (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        // Days 9-14 follow similar pattern, increasing intensity
        { day: 9, reading: 'Skim 2 passages, answer 15 questions (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Listen to 2 sections, note key points (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write 2 Task 2 paragraphs (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Practice 1 Part 2 question (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 10, reading: 'Skim 2 passages, answer 15 questions (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Listen to 2 sections, summarize (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Study Task 2 structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 Part 2 question (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 11, reading: 'Skim 2 passages, answer 15 questions (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Listen to 2 sections, note key points (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write 2 Task 2 paragraphs (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Practice 1 Part 2 question (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 12, reading: 'Skim 2 passages, answer 15 questions (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Listen to 2 sections, summarize (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Study Task 2 structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 Part 2 question (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 13, reading: 'Skim 2 passages, answer 15 questions (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Listen to 2 sections, note key points (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write 2 Task 2 paragraphs (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 Part 2 question (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 14, reading: 'Skim 2 passages, answer 15 questions (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Listen to 2 sections, summarize (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write 2 Task 2 paragraphs (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Practice 1 Part 2 question, review recording (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
      ],
      3: [
        { day: 15, reading: 'Full Reading test, review mistakes (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, check answers (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 full response (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 full Part 3, record and review (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        // Days 16-21 follow similar pattern
        { day: 16, reading: 'Full Reading test, review mistakes (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, check answers (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 full response (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 full Part 3 (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 17, reading: 'Full Reading test, review mistakes (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, check answers (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 full response (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 full Part 3 (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 18, reading: 'Full Reading test, review mistakes (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, check answers (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 full response (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 full Part 3 (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 19, reading: 'Full Reading test, review mistakes (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, check answers (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 full response (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 full Part 3 (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 20, reading: 'Full Reading test, review mistakes (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, check answers (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 full response (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice 1 full Part 3 (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 21, reading: 'Full Reading test, review mistakes (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, check answers (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 full response (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice 1 full Part 3, review recording (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
      ],
      4: [
        { day: 22, reading: '2 Reading passages, focus on speed (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 2 full response (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Practice full Speaking test, self-evaluate (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        // Days 23-28 follow similar pattern
        { day: 23, reading: '2 Reading passages, focus on speed (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 2 full response (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice full Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 24, reading: '2 Reading passages, focus on speed (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 2 full response (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice full Speaking test (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 25, reading: '2 Reading passages, focus on speed (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 2 full response (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Practice full Speaking test (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 26, reading: '2 Reading passages, focus on speed (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 2 full response (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Practice full Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 27, reading: '2 Reading passages, focus on speed (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 2 full response (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Practice full Speaking test (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 28, reading: '2 Reading passages, focus on speed (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: '2 Listening sections, improve accuracy (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 2 full response (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Practice full Speaking test, self-evaluate (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
      ],
      5: [
        { day: 29, reading: 'Full Reading test, time management (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, focus on details (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Mock Speaking test, work on coherence (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        // Days 30-35 follow similar pattern
        { day: 30, reading: 'Full Reading test, time management (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, focus on details (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Mock Speaking test (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 31, reading: 'Full Reading test, time management (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, focus on details (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Mock Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 32, reading: 'Full Reading test, time management (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, focus on details (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Mock Speaking test (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 33, reading: 'Full Reading test, time management (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, focus on details (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Mock Speaking test (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 34, reading: 'Full Reading test, time management (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, focus on details (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Mock Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 35, reading: 'Full Reading test, time management (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, focus on details (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, review structure (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Mock Speaking test, work on coherence (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
      ],
      6: [
        { day: 36, reading: 'Full Reading test, analyze errors (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Full Speaking test, focus on pronunciation (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        // Days 37-45 follow similar pattern, with 10 days in Week 6
        { day: 37, reading: 'Full Reading test, analyze errors (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, refine skills (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Full Speaking test (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 38, reading: 'Full Reading test, analyze errors (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Full Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 39, reading: 'Full Reading test, analyze errors (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Full Speaking test (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 40, reading: 'Full Reading test, analyze errors (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, refine skills (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Full Speaking test (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 41, reading: 'Full Reading test, analyze errors (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Full Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 42, reading: 'Full Reading test, analyze errors (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Full Speaking test (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
        { day: 43, reading: 'Full Reading test, analyze errors (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', listening: 'Full Listening test, refine skills (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/listening" class="text-blue-600 hover:underline">British Council</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://www.ieltsadvantage.com/writing-task-2/" class="text-blue-600 hover:underline">IELTS Advantage</a>)', speaking: 'Full Speaking test (<a href="https://www.ieltsbuddy.com/ielts-speaking.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)' },
        { day: 44, reading: 'Full Reading test, analyze errors (<a href="https://ieltsliz.com/ielts-reading-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ieltsbuddy.com/ielts-listening.html" class="text-blue-600 hover:underline">IELTS Buddy</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://www.cambridgeenglish.org/ielts/practice-tests/" class="text-blue-600 hover:underline">Cambridge</a>)', speaking: 'Full Speaking test (<a href="https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-practice-tests/speaking" class="text-blue-600 hover:underline">British Council</a>)' },
        { day: 45, reading: 'Full Reading test, analyze errors (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', listening: 'Full Listening test, refine skills (<a href="https://www.ielts.org/take-a-test/preparation-resources/free-practice-tests" class="text-blue-600 hover:underline">IELTS Official</a>)', writing: 'Write Task 1 & 2, improve vocabulary (<a href="https://ieltsliz.com/ielts-writing-task-1-lessons-and-tips/" class="text-blue-600 hover:underline">IELTS Liz</a>)', speaking: 'Full Speaking test, focus on pronunciation (<a href="https://ieltsliz.com/ielts-speaking-free-lessons/" class="text-blue-600 hover:underline">IELTS Liz</a>)' },
      ],
    };
  
    weekRows.forEach(row => {
      row.addEventListener('click', () => {
        const week = row.getAttribute('data-week');
        weekNumber.textContent = week;
        taskContent.innerHTML = '';
  
        tasks[week].forEach(task => {
          const dayDiv = document.createElement('div');
          dayDiv.className = 'task-day';
          dayDiv.innerHTML = `
            <h4>Day ${task.day}</h4>
            <ul>
              <li><strong>Reading (20-60 min):</strong> ${task.reading}</li>
              <li><strong>Listening (20-60 min):</strong> ${task.listening}</li>
              <li><strong>Writing (20-60 min):</strong> ${task.writing}</li>
              <li><strong>Speaking (20-60 min):</strong> ${task.speaking}</li>
            </ul>
          `;
          taskContent.appendChild(dayDiv);
        });
  
        // Show tasks with fade-in animation
        dailyTasks.classList.remove('hidden');
        setTimeout(() => dailyTasks.classList.add('show'), 10);
      });
    });
  
    // Hide tasks when clicking elsewhere
    document.addEventListener('click', (e) => {
      if (!e.target.closest('.week-row') && !e.target.closest('#daily-tasks')) {
        dailyTasks.classList.remove('show');
        setTimeout(() => dailyTasks.classList.add('hidden'), 500);
      }
    });
  });